name: Build FStar Binaries

on: [push]

jobs:

  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build binaries
      run: |
        export OPAMYES=1
        brew install opam
        opam init
        opam switch create 4.05.0
        opam install depext
        opam depext -i conf-gmp
        opam install ocamlbuild ocamlfind batteries stdint zarith yojson fileutils pprint menhir ulex ppx_deriving ppx_deriving_yojson process
        eval $(opam env)
        make -j -C src/ocaml-output
