name: Build FStar Binaries

on: [push]

jobs:

  build:

    runs-on: macos-latest

    steps:
    - name: Checkout everest
      uses: actions/checkout@v2
      with:
        repository: project-everest/everest
        path: everest
    - name: Checkout FStar
      uses: actions/checkout@v2
      with:
        path: FStar
    - name: Setup dependencies
      run: |
        cd everest
        export OPAMYES=1
        brew install opam bash gnu-getopt
        opam init
        opam switch create 4.05.0
        eval $(opam env)
        ./everest --yes z3 opam
        cd -
    - name: Build FStar
      run: |
        cd FStar
        make -j all
        cd -
    - name: Package FStar
      run: |
        cd FStar
        make -j package
        cd -
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: fstar_package
        path: FStar/src/ocaml-output/fstar_0.9.7.0-alpha1_Darwin_x86_64.tar.gz
